install tools

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -10,6 +10,8 @@ jobs:
   test:
     name: Run
     runs-on: ubuntu-latest
+    env:
+      PYTHON_VERSION: '3.11'
     steps:
     - uses: actions/checkout@v4
     - name: Install dependencies
@@ -21,14 +23,29 @@ jobs:
           libxfixes-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev \
           wget build-essential libreadline-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev \
           libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev liblzma-dev \
-          libegl1
+          libegl1 libjxl-tools libavif-bin imagemagick libimage-exiftool-perl
+        cargo install oxipng
     - uses: getsentry/action-setup-venv@v2.1.0
       with:
-        python-version: '3.11'
+        python-version: ${{ env.PYTHON_VERSION }}
         cache-dependency-path: |
           requirements.txt
           requirements_test.txt
         install-cmd: pip install -r requirements.txt -r requirements_test.txt
+    - name: Link tools
+      env:
+        TOOLS: cjxl djxl jxlinfo cjpegli avifenc avifdec magick
+        TARGET: bin/linux
+      run: |
+        mkdir -p ${TARGET}
+
+        for TOOL in $TOOLS ; do
+          if ! command -v $TOOL >/dev/null ; then
+            echo "Missing tool $TOOL"
+            exit 1
+          fi
+          ln -sv $(command -v $TOOL) ${TARGET}
+        done
     - name: Run tests
       run: |
         export PYTHONPATH=$PYTHONPATH:.
